<?php

namespace AppBundle\Repository;

/**
 * StudentAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
