<?php

namespace AppBundle\Repository;

/**
 * StudentAssesmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentAssesmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
