<?php

namespace AppBundle\Repository;

/**
 * ValidAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
